### ISSUE TITLE
Issues calculating max independent set

### ISSUE THREAD

**Issue by enj** [networkx/networkx#2127]
`Python 2.7.11`
`networkx 1.11`

I have the following directed acyclic graph:

![DAG](https://cloud.githubusercontent.com/assets/7001223/15185853/c0cba98a-1768-11e6-9ef4-ae6f87dd59e4.png)

I wanted to calculate the max independent set of the transitive closure of this DAG (the nodes colored in green).

``` python
from networkx import Graph, DiGraph, transitive_closure
from networkx.algorithms.bipartite import hopcroft_karp_matching, to_vertex_cover

# Build the DAG
G = DiGraph()
G.add_edge("A", "C")
G.add_edge("A", "B")
G.add_edge("C", "E")
G.add_edge("C", "D")
G.add_edge("E", "G")
G.add_edge("E", "F")
G.add_edge("G", "I")
G.add_edge("G", "H")

tc = transitive_closure(G)
btc = Graph()

# Create a bipartite graph based on the transitive closure of G
for v in tc.nodes_iter():
    btc.add_node((0, v))
    btc.add_node((1, v))

for u, v in tc.edges_iter():
    btc.add_edge((0, u), (1, v))

matching = hopcroft_karp_matching(btc)
vertex_cover = to_vertex_cover(btc, matching)
independent_set = set(G) - {v for _, v in vertex_cover}
```

I am expecting independent set to be `set(['B', 'D', 'F', 'I', 'H'])` but it is `set(['A', 'B', 'D', 'F', 'I', 'H'])` instead.  I am either doing something wrong, or there is a bug in the `to_vertex_cover` function.

References:
- http://cs.stackexchange.com/a/16829
- http://cs.stackexchange.com/a/10303/5323
- http://stackoverflow.com/a/10304235
- https://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm
- https://en.wikipedia.org/wiki/Dilworth's_theorem
- https://en.wikipedia.org/wiki/K%C5%91nig%27s_theorem_(graph_theory) - Konig’s theorem proves an equivalence between a maximum matching and a minimum vertex cover in bipartite graphs.  A minimum vertex cover is the complement of a maximum independent set for any graph

**Comment by hagberg** [comment]
When I run your code (modifying nodes_iter -> nodes and edges_iter-> edges in the latest API) I get the result you expect.
```python 
$ ipython
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %paste
from networkx import Graph, DiGraph, transitive_closure
from networkx.algorithms.bipartite import hopcroft_karp_matching, to_vertex_cover

# Build the DAG
G = DiGraph()
G.add_edge("A", "C")
G.add_edge("A", "B")
G.add_edge("C", "E")
G.add_edge("C", "D")
G.add_edge("E", "G")
G.add_edge("E", "F")
G.add_edge("G", "I")
G.add_edge("G", "H")

tc = transitive_closure(G)
btc = Graph()

# Create a bipartite graph based on the transitive closure of G
for v in tc.nodes():
    btc.add_node((0, v))
    btc.add_node((1, v))

for u, v in tc.edges():
    btc.add_edge((0, u), (1, v))

matching = hopcroft_karp_matching(btc)
vertex_cover = to_vertex_cover(btc, matching)
independent_set = set(G) - {v for _, v in vertex_cover}
print(independent_set)
## -- End pasted text --
{'H', 'I', 'B', 'D', 'F'}
```

**Comment by enj** [comment]
Could you try running it with `Python 2.7.11` and `networkx 1.11` (or possibly the latest API).  Perhaps there is a change since `1.11` that "fixed" this?  I am assuming it is not related to version of Python being used.

**Comment by hagberg** [comment]
I just looked at this again - aren't both answers valid?

**Comment by enj** [comment]
`A` and `B` cannot be in the same independent set because they share an edge (in both the original DAG and its transitive closure).  Also, it is impossible for both sets in my original post to be valid because they contain different numbers of nodes.  All valid maximum independent sets would have the same number of nodes, though the nodes do not have to be the same.

**Comment by hagberg** [comment]
Indeed, I see.  Let me try your suggested experiment.

**Comment by hagberg** [comment]
Interesting (bad).  I get the incorrect result with Python2 and correct result with Python3.  So there must be a bug somewhere.  Where? Maybe in the matching algorithm, @jfinkels?

```python
$ ipython2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %paste
from networkx import Graph, DiGraph, transitive_closure
from networkx.algorithms.bipartite import hopcroft_karp_matching, to_vertex_cover

# Build the DAG
G = DiGraph()
G.add_edge("A", "C")
G.add_edge("A", "B")
G.add_edge("C", "E")
G.add_edge("C", "D")
G.add_edge("E", "G")
G.add_edge("E", "F")
G.add_edge("G", "I")
G.add_edge("G", "H")

tc = transitive_closure(G)
btc = Graph()

# Create a bipartite graph based on the transitive closure of G
for v in tc.nodes():
    btc.add_node((0, v))
    btc.add_node((1, v))

for u, v in tc.edges():
    btc.add_edge((0, u), (1, v))

matching = hopcroft_karp_matching(btc)
vertex_cover = to_vertex_cover(btc, matching)
independent_set = set(G) - {v for _, v in vertex_cover}
print(independent_set)
## -- End pasted text --
set(['A', 'B', 'D', 'F', 'I', 'H'])

In [2]: matching
Out[2]: 
{(0, 'A'): (1, 'C'),
 (0, 'C'): (1, 'E'),
 (0, 'E'): (1, 'G'),
 (0, 'G'): (1, 'I'),
 (1, 'C'): (0, 'A'),
 (1, 'E'): (0, 'C'),
 (1, 'G'): (0, 'E'),
 (1, 'I'): (0, 'G')}

In [3]: vertex_cover
Out[3]: {(0, 'E'), (0, 'G'), (1, 'C'), (1, 'E')}

In [4]: import networkx

In [5]: networkx.__version__
Out[5]: '1.11'
````
```python
$ ipython3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %paste
from networkx import Graph, DiGraph, transitive_closure
from networkx.algorithms.bipartite import hopcroft_karp_matching, to_vertex_cover

# Build the DAG
G = DiGraph()
G.add_edge("A", "C")
G.add_edge("A", "B")
G.add_edge("C", "E")
G.add_edge("C", "D")
G.add_edge("E", "G")
G.add_edge("E", "F")
G.add_edge("G", "I")
G.add_edge("G", "H")

tc = transitive_closure(G)
btc = Graph()

# Create a bipartite graph based on the transitive closure of G
for v in tc.nodes():
    btc.add_node((0, v))
    btc.add_node((1, v))

for u, v in tc.edges():
    btc.add_edge((0, u), (1, v))

matching = hopcroft_karp_matching(btc)
vertex_cover = to_vertex_cover(btc, matching)
independent_set = set(G) - {v for _, v in vertex_cover}
print(independent_set)
## -- End pasted text --
{'F', 'B', 'I', 'D', 'H'}

In [2]: matching
Out[2]: 
{(0, 'A'): (1, 'C'),
 (0, 'C'): (1, 'D'),
 (0, 'E'): (1, 'F'),
 (0, 'G'): (1, 'H'),
 (1, 'C'): (0, 'A'),
 (1, 'D'): (0, 'C'),
 (1, 'F'): (0, 'E'),
 (1, 'H'): (0, 'G')}

In [3]: vertex_cover
Out[3]: {(0, 'A'), (0, 'C'), (0, 'E'), (0, 'G')}

In [4]: import networkx

In [5]: networkx.__version__
Out[5]: '1.11'
```

**Comment by jfinkels** [comment]
Can you provide just the (bipartite) graph that causes the problem and I'll take a look at it? Is the problem in the `maximum_matching` function or the `to_vertex_cover` function? Or is it not clear?

No way for me to know for sure but maybe there's an issue similar to that of #1927 (fixed by pull request #1955).

**Comment by jfinkels** [comment]
In the meantime, you can use `eppstein_matching` instead of `hopcroft_karp_matching`.

**Comment by hagberg** [comment]
I still get the same (bad) answer with the latest development version and Python2.

**Comment by enj** [comment]
I was originally under the impression that the problem was in the `to_vertex_cover` function because `eppstein_matching` and `hopcroft_karp_matching` returned similar results.  Now I am not sure (leaning towards the matching functions).

@jfinkels the code below will give you the bipartite graph in question.  Under Python 2 it gives the wrong result of `{'A', 'B', 'D', 'F', 'G'}` and under Python 3 it gives the correct result of `{'B', 'D', 'F', 'H', 'I'}`.

```python
from networkx import Graph
from networkx.algorithms.bipartite import eppstein_matching, to_vertex_cover

G = Graph()

G.add_nodes_from([(1, 'C'),
 (1, 'B'),
 (0, 'G'),
 (1, 'F'),
 (1, 'E'),
 (0, 'C'),
 (1, 'D'),
 (1, 'I'),
 (0, 'A'),
 (0, 'D'),
 (0, 'F'),
 (0, 'E'),
 (0, 'H'),
 (1, 'G'),
 (1, 'A'),
 (0, 'I'),
 (0, 'B'),
 (1, 'H')])

G.add_edge((1, 'C'), (0, 'A'))
G.add_edge((1, 'B'), (0, 'A'))
G.add_edge((0, 'G'), (1, 'I'))
G.add_edge((0, 'G'), (1, 'H'))
G.add_edge((1, 'F'), (0, 'A'))
G.add_edge((1, 'F'), (0, 'C'))
G.add_edge((1, 'F'), (0, 'E'))
G.add_edge((1, 'E'), (0, 'A'))
G.add_edge((1, 'E'), (0, 'C'))
G.add_edge((0, 'C'), (1, 'D'))
G.add_edge((0, 'C'), (1, 'I'))
G.add_edge((0, 'C'), (1, 'G'))
G.add_edge((0, 'C'), (1, 'H'))
G.add_edge((1, 'D'), (0, 'A'))
G.add_edge((1, 'I'), (0, 'A'))
G.add_edge((1, 'I'), (0, 'E'))
G.add_edge((0, 'A'), (1, 'G'))
G.add_edge((0, 'A'), (1, 'H'))
G.add_edge((0, 'E'), (1, 'G'))
G.add_edge((0, 'E'), (1, 'H'))

matching = eppstein_matching(G)
vertex_cover = to_vertex_cover(G, matching)
independent_set = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'} - {v for _, v in vertex_cover}
```

**Comment by enj** [comment]
Also, I just noticed that the Python 2 version is consistently wrong, but occasionally the Python 3 version will also give a wrong result such as `{'B', 'C', 'D', 'E', 'F'}`.  I had to run it a few times for it to give a wrong result.

**Comment by enj** [comment]
Actually that last comment can probably be ignored since I am using `1.11` and #1927 fixed the inconsistent behavior of `eppstein_matching`.

**Comment by enj** [comment]
As a test I tried using the matching data from Python 3 with the `to_vertex_cover` function in Python 2.  The Python 2 code still had the wrong results even with the "correct" matching data from Python 3.  Thus it may make more sense to focus on the `to_vertex_cover` function, to see why it behaves differently per Python version.

**Comment by hagberg** [comment]
I believe the bug is https://github.com/networkx/networkx/blob/master/networkx/algorithms/bipartite/matching.py#L415 with the call to bipartite.sets().  This partitioning by coloring isn't unique in your case and the bipartite sets it returns are not the ones you started with.   This breaks with both python2 and python3.  We were just lucky with Python3 that we got the correct partition.

**Comment by enj** [comment]
I get the same results from this function in both Python 2 and 3 (I can see that `(1, 'A')` is in the wrong set but I don't see how this is the cause of the issue if both versions of Python exhibit it):

```python
In [5]: networkx.bipartite.sets(G)
Out[5]:
({(1, 'B'),
  (1, 'C'),
  (1, 'D'),
  (1, 'E'),
  (1, 'F'),
  (1, 'G'),
  (1, 'H'),
  (1, 'I')},
 {(0, 'A'),
  (0, 'B'),
  (0, 'C'),
  (0, 'D'),
  (0, 'E'),
  (0, 'F'),
  (0, 'G'),
  (0, 'H'),
  (0, 'I'),
  (1, 'A')})

```

**Comment by hagberg** [comment]
The Python2 vs Python3 issue was just a distraction.   Python3 has added some hash randomization so the ordering of nodes produced (given the same input data) can vary.  We were just getting lucky that `bipartite.sets` was sometimes giving us the correct result.  If you adjust the line I mentioned above to (for your specific case to get the nodes correctly partitioned) 

    L = set([n for n in G if n[0]==0])
    R = set([n for n in G if n[0]==1])
#    L, R = bipartite_sets(G)

I believe it always works correctly.

The general fix is to specify the two node sets explicitly somehow - I haven't looked at this code design to see the best way to do that.  We sometimes use the node attribute part=0 part=1 to do that since there isn't a "BipartiteGraph" object in networkx.

**Comment by enj** [comment]
Ah I see what you mean.  Shouldn't the `color` function look to see if the graph has been explicitly partitioned via node attributes before trying to do the partitioning manually?

**Comment by hagberg** [comment]
I'm not sure that is the right place to fix this.  Perhaps in the `bipartite.sets` function or else in this case maybe in the `to_vertex_cover` function.

**Comment by enj** [comment]
I am not sure on this either.  I suggested `color` because `bipartite.sets` just calls that function anyway.  I don't think changing just `to_vertex_cover` would work because both matching functions also call `bipartite.sets`.

**Comment by jtorrents** [comment]
I think that the problem is that when the input graph is disconnected (as is @enj example), then two correct coloring are equally correct (see https://networkx.github.io/documentation/development/reference/algorithms.bipartite.html for more details), and `bipartite.sets` finds one or the other depending on the iteration order of the nodes in the graph (which depends on python version, and in python 3 is randomized).

In the bipartite package, many functions require a container of nodes with all nodes in one node set as argument to deal with this ambiguity. And the recommended practice is to use a node attribute named `bipartite` to keep track of which node set a node belongs.  Maybe the bipartite matching functions should also require one of the two node sets as argument. That will also allow us to skip a `bipartite.sets` call which will improve the running time for relatively large graphs.

**Comment by jfinkels** [comment]
@jtorrents Are you suggesting changing both the `hopcroft_karp_matching` function and the `to_vertex_cover` function to accept an additional argument, say `left_set`, that allows the user to explicitly specify the same "left set" in both functions?
