### ISSUE TITLE
nx.minimum_spanning_arborescence() runs too slow

### ISSUE THREAD

**Issue by sgreysond** [networkx/networkx#3825]
I'm having trouble getting the cost of the minimum spanning arborescence fast enough for large matrices in my application. Inside https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/tree/branchings.html , there is a TODO that references a Tarjan paper where an algorithm with better time-complexity is described. When will this actually be implemented?

**Comment by dschult** [comment]
As soon as someone writes it. ;}     Maybe you?

**Comment by parth-verma** [comment]
Adding to this, many of the algorithms (like modularity calculations, lfr benchmark generation) run very slow when dealing with large networks (around 1M nodes). Is there a possibility of releasing these are C interfaced codes so that they speed up?

**Comment by dschult** [comment]
Typically, getting the right algorithm is most important for speeding up code. We have tried C-interfaced code a few times (not with this part of the code) and the speedup was minimal. But we are hoping some changes to NetworkX over the next year might allow this type of interface.

More immediately and perhaps importantly, you can try Cython and Numba to speed up python code. Essentially they are converting to C without the headache of doing so.

**Comment by dschult** [comment]
Let me emphasize that this Issue requests a new, faster ALGORITHM to be implemented. Any potential fixers, please don't get distracted by the discussion about conversion to C.

The algorithm by Tarjan is what we'd like to have implemented.

**Comment by CyberMobius** [comment]
If it's not too much to ask, I think I could give implementing the Tarjan algorithm a shot.

**Comment by sgreysond** [comment]
> If it's not too much to ask, I think I could give implementing the Tarjan algorithm a shot.

That would be downright epic.

**Comment by edxu96** [comment]
I have implemented max (min) spanning arborescence and rank spanning arborescences based on [camerini1980ranking] for my master thesis. It seems that part for max (min) spanning arborescence is based on [tarjan1977finding], which I think it's the Tarjan algorithm you are referring.

Currently, my implementation is a bit ugly, but I can improve. @CyberMobius How is it going with your implementation? 

For rank spanning arborescences, I am going to open another issue.

---

- Camerini, P. M., Fratta, L., & Maffioli, F. (1980). Ranking arborescences in O (Km log n) time. European Journal of Operational Research, 4(4), 235-242.
- Tarjan, R. E. (1977). Finding optimum branchings. Networks, 7(1), 25-35.

**Comment by CyberMobius** [comment]
@edxu96 thanks so much for offering to help. I was making good progress on it until I ran into the section about creating a modified version of a "compressed tree" data structure. I was able to find a paper with a definition for the data structure the paper was talking about but now I'm unclear on how to actually use it in the context of the problem. I'm confident that if I could just work through this part of it I could finish the rest of it relatively smoothly. The good news is that I'm hopeful that this implementation will be performant.

I'll clean up what I have, push it up, and ask you more detailed questions about it once I have that up. Thanks again!

**Comment by edxu96** [comment]
I read [gabow1986efficient] mentioned in To-Do today. Compared to [camerini1980ranking], they describe the same algorithm in an efficient but implicit way. I understand what they are talking about, especially about "compressed tree". 

I can help fit that data structure in the context.

---

- Gabow, H. N., Galil, Z., Spencer, T., & Tarjan, R. E. (1986). Efficient algorithms for finding minimum spanning trees in undirected and directed graphs. Combinatorica, 6(2), 109-122.

**Comment by CyberMobius** [comment]
@edxu96 I've pushed up my code <https://github.com/CyberMobius/networkx/tree/spanning_arborescence> I only have a couple relatively small questions about them at this point. 

The paper doesn't say anything about how nodes are added to the Compressed Tree, I'm assuming every time we encounter a node in the growth path, we add it to the compressed tree with initial value 0, but I'm not sure. 
Secondly, when contracting nodes in a loop, do we need to create a new node to become the parent of all the contracted nodes or is it good enough to pick an arbitrary node to become the parent of the set containing all of the other contracted nodes? 

And lastly, I never found an explicit definition for the specific compressed tree datatype they used in this paper, I mostly assumed the details from [Tarjan1979Applications]. Most variants I saw didn't support `change_value(delta, a): add delta to the value of all elements in set A`. I'd appreciate a good source on this just to be sure of all the details.

---
* Robert Endre Tarjan. 1979. Applications of Path Compression on Balanced Trees. J. ACM 26, 4 (Oct. 1979), 690–715. DOI:https://doi.org/10.1145/322154.322161

**Comment by edxu96** [comment]
I need another 1-2 days to compare your code and understand [gabow1986efficient] completely. Will keep updating answers to your questions. Then we probably need a call to see how to proceed.

> how nodes are added to the Compressed Tree, I'm assuming every time we encounter a node in the growth path, we add it to the compressed tree with initial value 0, but I'm not sure.

My guess at the initial value is min value of its in-edges (directed into this vertex).

> Secondly, when contracting nodes in a loop, do we need to create a new node to become the parent of all the contracted nodes or is it good enough to pick an arbitrary node to become the parent of the set containing all of the other contracted nodes?

From the paper page 115: "the name of a set is the corresponding vertex in the contracted graph". The node is any one out of those contracted node, so you don't need a new node.

> Most variants I saw didn't support the `change_value(delta, a): add delta to the value of all elements in set A` operation. I'd appreciate a good source on this just to be sure of all the details.

It corresponds to a part in [camerini1980ranking], which is a simple operation, but I am not sure about `delta` right now. Probably you don't need to focus too much on formalisation.

**Comment by edxu96** [comment]
@CyberMobius I have submitted my thesis. Got time for this.

Here are 6 steps for the first phase of __max__ spanning arborescence in [camerini1980ranking]:

I tried to use data structures in [gabow1986efficient], because they are not used in [camerini1980ranking]. Two approaches look the same to me. Also, I have checked multiple times, but it seems that operations are the same as __min__ spanning arborescence.

Note \omega is weighting function of the original graph, which is in the right of the first line.

![Screenshot 2020-12-09 at 11 57 29](https://user-images.githubusercontent.com/19307850/101621343-ea074000-3a15-11eb-9687-48afe92fbf39.png)

**Comment by CyberMobius** [comment]
@edxu96 Congratulations on submitting your thesis! 

I looked through your answers and through the paper a little more and I feel good about continuing on the branch. I probably need to rewrite the compressed tree code to make it a little easier to use. I'll see if I can make some time later this week to finish out my first pass at the algorithm. Will keep you updated.

**Comment by sgreysond** [comment]
@CyberMobius @edxu96 Is anything still happening with this branch?

**Comment by CyberMobius** [comment]
@sgreysond So here's where it stands on my end. 

The algorithm to find the minimum spanning arborescence can be broken down into two parts. A contraction step, and an expansion step. The paper from Gabow et. al describes an improvement on the contraction step from Edmond's algorithm. This part I've mostly completed.

From here, I would need to implement the expanding step from Edmond's algorithm. The only problem I have is that the paper for Edmond's algorithm uses different terminologies for the same kind of structure making it hard for me to understand how to fit them together. In order to complete the work on this, I would need to go through both papers and sort it all out sometime.

I'm open to having someone take over the branch/PR and explaining what I've managed to learn from the papers, if it would help the issue resolve sooner. 
If not, I'll probably continue at an on and off pace on this branch until it's completed sometime in the future.

**Comment by edxu96** [comment]
@sgreysond Will have a look at @CyberMobius's fork. Should make it before the commencement of my job in April.
