### ISSUE TITLE
Irreproducible result from Louvain graph partitioning

### ISSUE THREAD

**Issue by hyperforest** [networkx/networkx#8095]
I have a weighted undirected graph. I partitioned the graph multiple times with Louvain algorithm, with SAME seed / random state across all runs, but it gives inconsistent result.

Is this expected? Is there any possible way to make it reproducible?

### Current Behavior

Attached script,  consuming `graph1.csv`, result in different partitioning (node set) when it's being run multiple times.

Output of the script:
```
Broken in iter: 5

Init. group:
[[23], [7], [1, 3, 12, 20, 33, 34, 35], [4, 5, 6, 16, 18, 19, 21, 22, 28, 29], [0, 2, 8, 9, 10, 11, 13, 14, 15, 17, 24, 25, 26, 27, 30, 31, 32, 36, 37]]

Group:
[[23], [7], [1, 3, 12, 17, 20, 31, 33, 34, 35], [4, 5, 6, 16, 18, 19, 21, 22, 28, 29], [0, 2, 8, 9, 10, 11, 13, 14, 15, 24, 25, 26, 27, 30, 32, 36, 37]]
```
### Expected Behavior

I do not know if it's expected or not, but if not, the partitioning must be consistent and reproducible whenever someone run it multiple times (as long as the seed / random state is same).

### Steps to Reproduce

Run the script below.

### Environment

Python version: `3.8.0`
NetworkX version: `2.8.8`
Conda: `4.10.1`
Numpy: `1.21.3`
Pandas: `2.0.3`

### Additional Context

The sample graph here has nodes of integer, while my actual graph nodes is string.

### Files

Graph (in .csv):
[graph1.csv](https://github.com/user-attachments/files/20577924/graph1.csv)

Script:
```
import numpy as np
import pandas as pd
import networkx as nx
import random


# random.seed(42)
# np.random.seed(42)


def load_graphs():
    df_graph = pd.read_csv('./graph1.csv')

    graph1 = nx.from_pandas_edgelist(
        df_graph,
        source='src',
        target='dst',
        edge_attr='weight',
        create_using=nx.Graph()
    )

    return graph1


def partition_graph(graph: nx.Graph, seed=None) -> list:
    group = nx.community.louvain_communities(graph, weight='weight', seed=seed)
    group = sorted(group, key=len)
    group = [sorted(g) for g in group]
    return group


if __name__ == '__main__':
    graph = load_graphs()

    random_state = np.random.RandomState(42)
    init_group = partition_graph(graph, seed=random_state)

    for it in range(100):
        group = partition_graph(graph, seed=random_state)

        if group != init_group:
            print(f'Broken in iter: {it}')
            
            print('\nInit. group:')
            print(init_group)
            
            print('\nGroup:')
            print(group)
            break
```

**Comment by hyperforest** [comment]
Tried this trick from [here](https://github.com/networkx/networkx/issues/6655), by changing this line in NetworkX 2.8.8 line 166:

from
`partition = [{u} for u in G.nodes()]`
to
`partition = [{u} for u in sorted(G.nodes())]`

Still the algorithm produce in inconsistent partitioning as well.

**Comment by rossbar** [comment]
A couple things immediately come to mind:
 1. NX 2.8.8 is quite old and no longer supported. There have been updates to `louvain` since then that may have fixed this problem, such as it is.
 2. Do you have floating point weights? Precision issues could in principle cause non-deterministic behavior

**Comment by hyperforest** [comment]
> A couple things immediately come to mind:
> 
> 1. NX 2.8.8 is quite old and no longer supported. There have been updates to `louvain` since then that may have fixed this problem, such as it is.
> 2. Do you have floating point weights? Precision issues could in principle cause non-deterministic behavior

@rossbar 

Tried to upgrade NetworkX to `3.1` (latest compatible version for Python 3.8 according to [here](https://networkx.org/documentation/stable/release/release_3.1.html)).

Tried to set the weight as integer as well -- basically multiplying the weights of the sample graph above with 100, then rounded it down.

However the issue is still happened (now with different output).

```
Broken in iter: 7

Init. group:
[[23], [7], [1, 3, 12, 17, 20, 31, 32, 33, 34, 35], [4, 5, 6, 16, 18, 19, 21, 22, 28, 29], [0, 2, 8, 9, 10, 11, 13, 14, 15, 24, 25, 26, 27, 30, 36, 37]]

Group:
[[23], [7], [4, 5, 6, 16, 18, 19, 21, 22, 28, 29], [1, 3, 12, 17, 20, 31, 32, 33, 34, 35], [0, 2, 8, 9, 10, 11, 13, 14, 15, 24, 25, 26, 27, 30, 36, 37]]
```

So I think it's not an issue of NetworkX version or floating point precision of the weights.

In a case where the Python version have to be 3.8 and can not be moved to the newer version, any solution for this?

**Comment by hyperforest** [comment]
Furthermore, I noticed that Louvain has the `py_random_state("seed")` decorator.

This is being used further in `seed.shuffle(rand_nodes)`, in the `_one_level` function, in `louvain.py` line 235 in NetworkX 3.1.

This decorator involves the `create_py_random_state` function from `networkx/utils/misc.py`.

Traced a little and found `PythonRandomInterface` class from `networkx/utils/decorators.py`.

Tried to do this, and it gives different result:
```
import numpy as np

rng = PythonRandomInterface(rng=np.random.RandomState(42))

a = list(range(10))
rng.shuffle(a)

for it in range(100):
    b = list(range(10))
    rng.shuffle(b)

    if a != b:
        print(f"Broken at iter {it}")
        print(a)
        print(b)
        break
```

Output:
```
Broken at iter 0
[8, 1, 5, 0, 7, 2, 9, 4, 3, 6]
[0, 1, 8, 5, 3, 4, 7, 9, 6, 2]
```

Is it supposed to be not happened?

I suspect that by using this decorator, everytime one is trying to call the Louvain partitioning, a new interface is instantiated, resulting in a different partitioning even when the seed is set.

***

EDIT:

By doing this:
1. Removing the `py_random_state("seed")` decorator in `louvain_communities` and `louvain_partitions` functions in `louvain.py`
2. Change `seed.shuffle(rand_nodes)` to `rng = np.random.RandomState(seed); rng.shuffle(rand_nodes)`, in the `_one_level` function in `louvain.py` (using `random.Random(seed)` also can do)
3. Change the script in the beginning of the thread to `random_state = 42` from `random_state = np.random.RandomState(42)`, and run the loop for 1000 times

... now the result is deterministic! 🎉❓

In this case, if we want to make a reproducible result for Louvain, isn't it better to do either:
1. Change the random state shuffling to directly use `random.Random` or `np.random.RandomState`, or
2. Fix the `py_random_state` decorator?

**Comment by rossbar** [comment]
> I suspect that by using this decorator, everytime one is trying to call the Louvain partitioning, a new interface is instantiated, resulting in a different partitioning even when the seed is set.

If you use an integer seed, then the machinery is creating a consistent random state (either with NumPy or `random`) at each call from that integer, so there should be no variation. The only exception would be if there were a call to either `random` or `np.random` directly, which I don't see in the source code.

For reproducibility, you should definitely pass in integer seeds (or explicitly seeded random states, like `seed=np.random.default_rng(my_seed)`) to ensure you are avoiding any sort of global random state.

I'm still not convinced there's a problem that hasn't already been fixed in subsequent NX versions - there's nothing we can do to help with bugs in 2.8.8 or 3.1.

**Comment by amcandio** [comment]
Don't you need to recreate the seed every time you call the method?
Otherwise you are not really passing the same random state.

**Comment by dschult** [comment]
I agree with @amcandio. The problem is with how you are setting your seeds.

Both the test in the original post and the test you wrote for `PythonRandomInterface` set the seed only once at the beginning. So it **should** give different results on each iteration of the loop. To get the same results you have to reset the seed before the second call.

Just FYI, this code has the same behavior with the latest version of NetworkX. It gives different results (because the state of the random number generate has changed).  You need to add a line:
```python
    random_state = np.random.RandomState(42)
    init_group = partition_graph(graph, seed=random_state)

    for it in range(100):
        random_state = np.random.RandomState(42)  #######  <---- add this inside the loop to reset the rng state.

        group = partition_graph(graph, seed=random_state)

        if group != init_group:
            print(f'Broken in iter: {it}')
            
            print('\nInit. group:')
            print(init_group)
            
            print('\nGroup:')
            print(group)
            break
```

**Comment by supreethmv** [comment]
@amcandio and @dschult are right.

@hyperforest although your code results in different partitions, it’s still reproducible in the sense that it consistently produces the same output for a given seed. In your example, loop always break on the 5th iteration. 

In addition to the approach suggested by @dschult, @rossbar also suggested a simpler (and more conventional) alternative to use a fixed integer seed instead of a `RandomState` object. For example:

```python
random_state = 42
init_group = partition_graph(graph, seed=random_state)

for it in range(100):
    group = partition_graph(graph, seed=random_state)

    if group != init_group:
        print(f'Broken in iter: {it}')
        print('\nInit. group:')
        print(init_group)
        print('\nGroup:')
        print(group)
```

@rossbar I guess you can be convinced that there's no problem :)

**Comment by rossbar** [comment]
It looks like this one has been cleared up, so I'll close it. Thanks @amcandio @dschult and @supreethmv for taking a closer look at the example in the OP to find the issue!

**Comment by hyperforest** [comment]
Hi all,

The problem seems to be solved when I upgrade my Python to `3.10.0` and NetworkX to `3.4.2`, and passing an integer for the `seed` argument to the Louvain function.

Thank you so much for the discussion, and special thanks to the maintainers and moderators.
